.\"     Title: idmap_nss
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2008
.\"    Manual: ã\(mdã\(S1ãã\ ç\(rg\(r!çãã\(14ã\(Fo
.\"    Source: Samba 3.2
.\"
.TH "IDMAP_NSS" "8" "11/13/2008" "Samba 3\.2" "ã\(mdã\(S1ãã\ ç\(rg\(r!çãã\(14ã\(Fo"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
idmap_nss - Sambaã\(rgWinbindç\(adidmap_nssããã\(a-ã\(adã\(S3ã
.SH "è\(Of\(noæ"
.PP
idmap_nss ãã\(coã\(deã\(Csã\(S3ãä\(12\(r?ãã\(adãUnix ã\(rgã\(bbã\(14ã\(psã\(14ã\(adã\(deã\(Foã\(14ãã Windows ã\(rgã\(ctã\(Foã\(bbã\(S3ãã\(Foãããã\(S3ã\(deã\(scããããã\(Foã\(Ofããsmb\.conf ã\(rg "winbind trusted domains only" ã\(Ofãã\(mdã\(scã\(S3ã\(a-ç\(r!å\(S1ã\(adã\(Ofãã ããã\(Foããããã\(adãã\(de Unix å\(aaã\(sc jsmith ã\(adããååã\(Foã\(Ofã\(Poã\(bbããã\(bbã\(14ã\(psã\(14ã\(rg SID ãã DOMAIN\ejsmith ã\(rg SID ã\(adãã\(bbå\(S2ãå\(12ã\(bbããã\(bbããã\(adãã\(Poããã\(adã ç\(de\(r!åã\(Foç\(ct\(Omè\(Ofã\(scããããã\(Foã\(Ofããããã\(a- Samba ã\(rgã\(r!ã\(S3ãã\(14ã\(mcã\(14ãã\(14ä\(acã\(Foãã ãã\(r!ã\(Csã\(Foããã\(Ofã\(S3ã\(r?å\(+-æã\(Foããã\(bbãACL ã\(rgè\(r!\(adç\(Cs\(Omãè\(r!ãã\(rgã\(Foå\(r?è\(bbã\(Ofæå\ \(+-ã\(scããã
.SH "ä\(12\(r?ç\(adä\(34"
.PP
ãã\(rgä\(34ã\(scã\(a-ããã\(r!ã\(Csã\(S3ãææããã\%ã\(14ã\(Foã\(Foã\(ctã\(Foã\(bbã\(S3ãã idmap_nss ã\(sc ãã\(scãã\(a-ããä\(acæ\(S1ã\(scãä\(r?\(r!é\ \(14ããããã\(r!ã\(Csã\(S3ã\(Foé\(ctããæ\(deãããããã\(S3ã\(deã\(Foã\(Csãã\(bbã\(a-ã å\(S2ãå\(12ã\(bbç\(a-å\(S2ãä\(12\(r?ã\(Poã\(bbä\(12æããæ\(S1æ\(S3ãç\(Cs\(Omãã\(bbããã
.sp
.RS 4
.nf
	[global]
	    idmap domains = SAMBA TRUSTEDDOMAINS

	    idmap config SAMBA:backend  = nss
	    idmap config SAMBA:readonly = yes

	    idmap config TRUSTEDDOMAINS:default = yes
	    idmap config TRUSTEDDOMAINS:backend = tdb
	    idmap config TRUSTEDDOMAINS:range   = 10000 \- 50000

	    idmap alloc backend      = tdb
	    idmap alloc config:range = 10000 \- 50000
	
.fi
.RE
.SH "ä\(12è"
.PP
ã\(Ofã\(Ofã\(acãã\(Foã\(rg Samba ã\(12ããã\(bbã\(scã\(ctã\(adããã\(Foé\(cté\(Poããã\(bbã\(14ãã\(Poã\(Ofãã\(Poã\(14ã\(a-ã Andrew Tridgell ã\(Foãã\(Poã\(bbä\(12ããããSamba ã\(a-ç\(34å\(adãLinux ã\(Foã\(14ãã\(Foéç\(Omã\(ad åæ\(scã\(rgæ\(S1æ\(S3ã\(scãSamba Team ã\(Foããã\(Ofã\(14ãã\(S3ã\(12ã\(14ã\(S1ãã\%ã\(acã\(scã\(a-ãã\(adãã\(bb éç\(Omããã\(bbããã
.SH "æ\(Yeæ\(noè\(Ofè\(ad\(S3"
.PP
ãã\(rgããã\(Yeã\(ctã\(Foãã\(14ã\(acã\(a- Samba 3\.2\.4 å\(a-\(34å\(r?ã\(rgãã\(rgã\(scããã
.PP
ãã\(rgãã\%ã\(Yeã\(r!ã\(S3ãã\(rg Samba 3\.2\.4 å\(a-\(34å\(r?ã\(rgç\(r?\(Fcè\(ad\(S3ã\(a-
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
å\ ç\(de å\(Foè\(+-(hotta@net\-newbie\.com)
.sp
.RE
ã\(Foãã\(Poã\(bbè\(r!ã\(Ofãããã
