.\"     Title: idmap_ldap
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2008
.\"    Manual: ã\(mdã\(S1ãã\ ç\(rg\(r!çãã\(14ã\(Fo
.\"    Source: Samba 3.2
.\"
.TH "IDMAP_LDAP" "8" "11/13/2008" "Samba 3\.2" "ã\(mdã\(S1ãã\ ç\(rg\(r!çãã\(14ã\(Fo"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
idmap_ldap - Sambaã\(rgWinbindç\(adidmap_ldapããã\(a-ã\(adã\(S3ã
.SH "è\(Of\(noæ"
.PP
idmap_ldap ãã\(coã\(deã\(Csã\(S3ã\(a-ã LDAP ãã\(Poã\(noã\(a-ãã\(Ofã\(mcã\(14ãã\(S1ã\(Foãã SID/uid/gid ã\(rgãããã\(S3ã\(deãã\(14ãã\(Foã\(Foå\(a-\(34ãã\(bbã Winbind ããæ\ \(14ç\(aaï\(14 å\(14ã\(S3å\(Omããè\(r!ãææ\(rg\(mcãæä\(34ããããã\(rgã\(ctã\(acã\(Yeã\(14ã\(Foã\(a- "idmap" ã\(ad "idmap alloc" API ã\(rgä\(ac\(r!æ\(S1ãå\(rgè\(Poãã\(bbããã
.SH "IDMAP ã\(Ofãã\(mdã\(scã\(S3"
.PP
ldap_base_dn = DN
.RS 4
SID/uid/gid ãããã\(S3ã\(deã\(adã\(S3ãã\(Ofã\(rgæ\(Csç\(aa\(ctãè\(r!ãéã\(Foä\(12\(r?ç\(adããã ãã\(Poã\(noã\(a-ãã\(Ofã\(rg base suffix ãå\(rgç\(34\(coãããå\(rgç\(34\(coããã\(bbãã\(Ofãå\ \(aaåã idmap_ldap ã\(a-ããã\(coã\(Foãã\(sc smb\.conf ã\(rg "ldap idmap suffix" ã\(Ofãã\(mdã\(scã\(S3ã\(rgå\(Csãä\(12\(r?ç\(adããã
.RE
.PP
ldap_user_dn = DN
.RS 4
è\(Ofè\(ad\(14ã\(rgéã\(Foä\(12\(r?ç\(adãã user DN ãå\(rgç\(34\(coããã æ\(Ofå\(rgç\(34\(coã\(rgå\ \(aaåã\(a-å\(r?åãã\(Csã\(S3ããå\(rgè\(r!ãããã
.RE
.PP
ldap_url = ldap://server/
.RS 4
æ\(ctå\%ã\(rg SID/uid/gid ãããã\(rgã\(adã\(S3ãã\(Ofãæ\(Csç\(aa\(ctããéã\(Foä\(12\(r?ç\(adãã LDAP ã\(mcã\(14ãã\(14ãæå\(rgãããæ\(Ofå\(rgç\(34\(coã\(rgå\ \(aaåã ldap://localhost/ ãä\(12\(r?ãããã
.RE
.PP
range = low \- high
.RS 4
ããã\(a-ã\(adã\(S3ããæ\(ad\(coå\(adãæã\(Csã\(adè\(bbå\(rgããã\(bbããã uid ã\(ad gid ã\(rgå\(coç\(adå\(a-è\(12ã\(Of ãããã\(S3ã\(deç\(a-å\(S2ãå\(rgç\(34\(coãããä\(Omå\(rgä\(acåãããã\(a-ã\(adã\(S3ãã SID/uid/gid ãããã\(S3ã\(deã\(rgã\(adã\(S3ãã\(Ofãæ\ \(14ç\(aaï\(14å\(14ã\(S3å\(Omããããããéå\(ac\(acãã\(rgç\(a-å\(S2ã\(a- å\(S2ãå\(12ã\(bbç\(a-å\(S2ã\(adåãã\(Foã\(Ofããæå\(rgãã\(Ofãå\ \(aaå Winbind ã\(a-ãã\(scã\(Csã\(Fo ã\(Ofã\(14ãã\(14ãã\(bbã smb\.conf ã\(rg "idmap uid" ã\(ad "idmap gid" ã\(Ofãã\(mdã\(scã\(S3ãä\(12\(r?ç\(adããã
.RE
.SH "IDMAP ALLOC ã\(Ofãã\(mdã\(scã\(S3"
.PP
ldap_base_dn = DN
.RS 4
ãã\(rgãã\(Poã\(noã\(a-ãã\(Ofã\(rgä\(ac\%ã\(scãæ\(deãã SID/uid/gid ãããã\(S3ã\(deã\(rgã\(adã\(S3ãã\(Ofã æ\ \(14ç\(aaããã\(S1ã base suffix ãå\(rgç\(34\(coãããæå\(rgãã\(Ofãå\ \(aaåã idmap_ldap ã\(a- ããã\(coã\(Foãã\(adãã\(bb smb\.conf ã\(rg "ldap idmap suffix" ã\(Ofãã\(mdã\(scã\(S3ãä\(12\(r?ç\(adããã
.RE
.PP
ldap_user_dn = DN
.RS 4
è\(Ofè\(ad\(14ã\(rgéã\(Foä\(12\(r?ç\(adããuser DNãå\(rgç\(34\(coããã æ\(Ofå\(rgç\(34\(coã\(rgå\ \(aaåã\(a-å\(r?åãã\(Csã\(S3ããå\(rgè\(r!ãããã
.RE
.PP
ldap_url = ldap://server/
.RS 4
modify/add/delete ã\(Ofã\(a-ã\(adã\(S1ããéä\(r?\(r!ããå\(rgåã\(adãã\(bbã\(rg LDAP ã\(mcã\(14ãã\(14 ãæå\(rgãããæ\(Ofå\(rgç\(34\(coã\(rgå\ \(aaå ldap://localhost/ ãä\(12\(r?ãããã
.RE
.PP
range = low \- high
.RS 4
winbindd ããã\(bbã\(14ã\(psã\(adã\(deã\(Foã\(14ãã\(Foå\(a-\(34ãã\(bbå\(S2ãå\(12ã\(bbãã\(scãã uid ã\(ad gid ã\(rgå\(coç\(adå\(a-è\(12ç\(a-å\(S2ãå\(rgç\(34\(coãããæå\(rgãã\(Ofãå\ \(aaå Winbind ã\(a-ãã\(scã\(Csã\(Fo ã\(Ofã\(14ãã\(14ãã\(bbã smb\.conf ã\(rg "idmap uid" ã\(ad "idmap gid" ã\(Ofãã\(mdã\(scã\(S3ãä\(12\(r?ç\(adããã
.RE
.SH "ä\(12\(r?ç\(adä\(34"
.PP
ä\(Fc\(Yeä\(acã\(rg LDAP è\(ad\%å\(rgã\(rgä\(34ã\(a-ãSID/gid/uid ãããã\(S3ã\(deãé\(Foéã\(Foæ\(Csç\(aa\(ctããããã\(Fo localhost ä\(acã\(scåä\(12ãã\(bbããã\(S1ã\(noã\(14ãã\(mcã\(14ãã\(14ã\(rgãã\(rgã\(scãããç\(aa\(S1ä\(Fc(referral) ã\(rgè\(ad\%å\(rgãæ\%\(Poããã\(Ofããã\(bbãããã\(adãæã\(Foç\(Cs\(Omãã\(bbããã idmap å\(S2å\(12ã\(bbç\(adããã\(a-ã\(adã\(S3ãã\(a-ç\(aaæ\(Yeãã\(S1ã\(r?ã\(14ãæãã\(bbãããç\(aa\(S1ä\(Fcï\(14ã\(adããã\(Fo ç\(psããã\(S1ã\(r?ã\(14ã\(acã\(rgåæ\(Yeç\(psï\(14ã\(a-ã\(S1ã\%ããããããããã\(Foãããã\(S1ã\(noã\(14ãã\(a- å\(S2ãå\(12ã\(bbè\(bbæ\(+-ã\(rgç\(mcæã\(adãã\(bbãã\(S1ã\(r?ã\(14å\(aaã\(scæ\(acãè\(34\(14ã\(34ãããã\(rgãè\(r?ãã\(bbãããã
.sp
.RS 4
.nf
	[global]
	    idmap domains = ALLDOMAINS
	    idmap config ALLDOMAINS:default      = yes
	    idmap config ALLDOMAINS:backend      = ldap
	    idmap config ALLDOMAINS:ldap_base_dn = ou=idmap,dc=example,dc=com
	    idmap config ALLDOMAINS:ldap_url     = ldap://localhost/
	    idmap config ALLDOMAINS:range        = 10000 \- 50000

	    idmap alloc backend = ldap
	    idmap alloc config:ldap_base_dn = ou=idmap,dc=example,dc=com
	    idmap alloc config:ldap_url     = ldap://master\.example\.com/
	    idmap alloc config:range        = 10000 \- 50000
	
.fi
.RE
.SH "åè"
.PP
LDAP ã\(mcã\(14ãã\(14ã\(Foå\(a-\(34ãã\(bbè\(Ofè\(ad\(14ãä\(12\(r?ç\(adããã\(Foã\(a- DN ã\(adãã\(S1ã\(a-ã\(14ãã æå\(rgããå\(r?è\(bbãããã\ ãããè\(ad\%å\(rgãã\(r!ã\(Csã\(Foä\(ac\%ã\(Foå\(S1\(S3æã\(scæå\(rgããã ãã\(S1ã\(a-ã\(14ããæããã\(bbãã\(34ããã\(adãé\(S2ãããã\(Foããããã\(a-ã\(Fcã\%ã\(Yeã\(Ofãã\(Po ã\(S1ãã\(ctã\(rgä\(ac\%ã\(Foæ\ \(14ç\(aaããããç\(S1å\(rgã\(rg idmap ãã\(r!ã\(Csã\(S3ã\(Foããã\(bbãæå\(rgããã DN ã\(Foå\(a-\(34ããç\(scå\(a-ã\(rgãã\(S1ã\(a-ã\(14ããæ\ \(14ç\(aaããã\(Foã\(a- "net idmap " ã\(S3ãã\(S3ããä\(12\(r?ç\(adããã
.SH "ä\(12è"
.PP
ã\(Ofã\(Ofã\(acãã\(Foã\(rg Samba ã\(12ããã\(bbã\(scã\(ctã\(adããã\(Foé\(cté\(Poããã\(bbã\(14ãã\(Poã\(Ofãã\(Poã\(14ã\(a-ã Andrew Tridgell ã\(Foãã\(Poã\(bbä\(12ããããSamba ã\(a-ç\(34å\(adãLinux ã\(Foã\(14ãã\(Foéç\(Omã\(ad åæ\(scã\(rgæ\(S1æ\(S3ã\(scãSamba Team ã\(Foããã\(Ofã\(14ãã\(S3ã\(12ã\(14ã\(S1ãã\%ã\(acã\(scã\(a-ãã\(adãã\(bb éç\(Omããã\(bbããã
.SH "æ\(Yeæ\(noè\(Ofè\(ad\(S3"
.PP
ãã\(rgããã\(Yeã\(ctã\(Foãã\(14ã\(acã\(a- Samba 3\.2\.4 å\(a-\(34å\(r?ã\(rgãã\(rgã\(scããã
.PP
ãã\(rgãã\%ã\(Yeã\(r!ã\(S3ãã\(rg Samba 3\.2\.4 å\(a-\(34å\(r?ã\(rgç\(r?\(Fcè\(ad\(S3ã\(a-
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
å\ ç\(de å\(Foè\(+-(hotta@net\-newbie\.com)
.sp
.RE
ã\(Foãã\(Poã\(bbè\(r!ã\(Ofãããã
