.\"     Title: idmap_rid
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2008
.\"    Manual: ã\(mdã\(S1ãã\ ç\(rg\(r!çãã\(14ã\(Fo
.\"    Source: Samba 3.2
.\"
.TH "IDMAP_RID" "8" "11/13/2008" "Samba 3\.2" "ã\(mdã\(S1ãã\ ç\(rg\(r!çãã\(14ã\(Fo"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
idmap_rid - Sambaã\(rgWinbindç\(adidmap_ridããã\(a-ã\(adã\(S3ã
.SH "è\(Of\(noæ"
.PP
idmap_rid ããã\(a-ã\(adã\(S3ãã\(a-ãUID ã GID ã\(ad SID ãå\(a-\(34å\(r?ä\(Fcããããã\(rg æ\(S1æ\(S3ã\(rgã\(S2ã\(adã\(Csã\(adãã\(bbãã\(ctã\(Foã\(aaã\(Ofã\(Omã\ çã\(Ofãããã\(S3ã\(deã\(rgä\(Fcç\(mcã\(r?ãæä\(34ããã ãã\(rgã\(+-ã\(14ã\(S1ã\(scã\(a-æ\(+-\(Omå\(rgè\(Foçã\(Ofãããã\(S3ã\(deãè\(r!ãããããã\(14ã\(r?ãã\(14ã\(S1ãå\(r?è\(bb ã\(adãã\(Ofãã
.SH "IDMAP ã\(Ofãã\(mdã\(scã\(S3"
.PP
range = low \- high
.RS 4
ããã\(a-ã\(adã\(S3ããæ\(ad\(coå\(adãæã\(Csã\(adè\(bbå\(rgããã\(bbãããuid ã\(ad gid ã\(rgå\(coç\(adå\(a-è\(12ã\(Of ãããã\(S3ã\(deç\(a-å\(S2ãå\(rgç\(34\(coããããã\(rgç\(a-å\(S2ã\(a-ãã\(Poã\(Foã\(r?ã\(14ã\(adãã\(bbåä\(12ãããã\(adã\(Fo æ\(S3\(adæãããããUID ã\(ad GID ã\(rgè\(adç\(rgç\(mcæãã\(ctã\(Foã\(aaã\(Ofã\(Omã\ çã\(Foãã\(rgç\(a-å\(S2å\(Cs ã\(Foã\(Ofã\(Poã\(bbãã\(34ã\(Poãå\ \(aaåããããã\(a-ç\(r!è\(bbãããå\(a-\(34å\(r?ãããããã\(a-ç\ \(aaæ\(Poãããã ãã\(rgã\(Ofãã\(mdã\(scã\(S3ã\(a-ãUID ã GID ããã\(34ãã\(34ã\%ã\(14ã\(Foã\(Foã\(adã\(Ofã\(ctã\(14ãã\(scãããã å\(rgç\(34\(coããã ID ã\(adéè\(Csãã\(bbãã\(34ãã\(rgãé\(r?ããããã\(Foç\(adæããã\(bbããã
.RE
.PP
base_rid = æ\(deå\%
.RS 4
UID ã GID ãã SID ãçæããããåå\(34ããSID ãã UID ã GID ã æ\(+-ãããããããã\(rgãã\(14ã\(S1ã\(adã\(Ofãæ\(aaæ\(deãæå\(rgãããã\(bbã\(14ã\(psã\(rg RID ã\(a- ããã\(coã\(Foãã\(scã\(a- 1000 (16é\(S2ã\(scã\(a-512) ããå\(scã\(34ãããã\(rgãããbase_rid ã\(rgå\(Ye\(12ã\(34ããå\(Csã\(a- 1000 ã\(adã\(Ofããããã\(Foããç\(mcæã\(adãã\(bbã\(rg ID ã\(a- ID = RID \- BASE_RID + LOW RANGE ID ã\(adãã\(bbç\(rgå\(Omã\(scããã
.RE
.SH "ä\(12\(r?ç\(adä\(34"
.PP
ãã\(rgä\(34ã\(scã\(a- idmap_rid ã\(scï\(14ã\(Csã\(rgãã\(r!ã\(Csã\(S3ãè\(ad\%å\(rgãã\(bbããã
.sp
.RS 4
.nf
	[global]
	    idmap domains = MAIN TRUSTED1

	    idmap config MAIN:backend      = rid
	    idmap config MAIN:base_rid     = 0
	    idmap config MAIN:range        = 10000 \- 49999

	    idmap config TRUSTED1:backend  = rid
	    idmap config TRUSTED1:base_rid = 1000
	    idmap config TRUSTED1:range    = 50000 \- 99999
	
.fi
.RE
.SH "ä\(12è"
.PP
ã\(Ofã\(Ofã\(acãã\(Foã\(rg Samba ã\(12ããã\(bbã\(scã\(ctã\(adããã\(Foé\(cté\(Poããã\(bbã\(14ãã\(Poã\(Ofãã\(Poã\(14ã\(a-ã Andrew Tridgell ã\(Foãã\(Poã\(bbä\(12ããããSamba ã\(a-ç\(34å\(adãLinux ã\(Foã\(14ãã\(Foéç\(Omã\(ad åæ\(scã\(rgæ\(S1æ\(S3ã\(scãSamba Team ã\(Foããã\(Ofã\(14ãã\(S3ã\(12ã\(14ã\(S1ãã\%ã\(acã\(scã\(a-ãã\(adãã\(bb éç\(Omããã\(bbããã
.SH "æ\(Yeæ\(noè\(Ofè\(ad\(S3"
.PP
ãã\(rgããã\(Yeã\(ctã\(Foãã\(14ã\(acã\(a- Samba 3\.2\.4 å\(a-\(34å\(r?ã\(rgãã\(rgã\(scããã
.PP
ãã\(rgãã\%ã\(Yeã\(r!ã\(S3ãã\(rg Samba 3\.2\.4 å\(a-\(34å\(r?ã\(rgç\(r?\(Fcè\(ad\(S3ã\(a-
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
å\ ç\(de å\(Foè\(+-(hotta@net\-newbie\.com)
.sp
.RE
ã\(Foãã\(Poã\(bbè\(r!ã\(Ofãããã
