.\"     Title: vfs_gpfs
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/06/2008
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "VFS_GPFS" "8" "11/06/2008" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_gpfs - gpfs に特化した Samba の機能拡張を行なう。like acls and prealloc
.SH "SYNOPSIS"
.HP 1
vfs objects = gpfs
.SH "説明"
.PP
この VFS モジュールは
\fBsamba\fR(7)
システムの一部である。
.PP

gpfs
VFS モジュールは、Samba が GPFS と適切に連携する上で必要となる様々な GPFS エクステンションの モジュールのベースである。 GPFSによって提供されるGPLライブラリインタフェースを使う。
.PP
現在のところ、gpfs VFS モジュールは以下のエクステンションのみを提供している:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
GPFSのために設定可能なNFSv4 ACL インタフェース
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
GPFS によるカーネル oplock のサポート
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
GPFS による lease サポート
.sp
.RE
.PP
注意:このモジュールは POSIX ACL の挙動を模しているため、chown によるパーミッションの変更が可能である。 しかし、 Samba は現在のところ、この動作をサポートしていない。 このモジュールによる chown を禁止するには、Samba よりも下位の ファイルシステム側の責任となる。
.PP
このモジュールはスタック可能である。
.SH "オプション"
.PP
nfs4:mode = [ simple | special ]
.RS 4
GPFS上の特別なIDの置き換えを有効/無効にする。このパラメータはどのような方法でも windowsのユーザに影響を与えるべきでない。これは、Sambaに、GPFSに関連のある OWNER@とGROUP@(単純なuidへのマッピング)である特別なIDを設定することのみを 確実にする。
.sp
以下のモードはモジュールによって解釈される:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
simple(既定値)
\- GPFS　ACE中で特別なIDを使わない
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
special
\- GPFS ACE中で特別なIDを使う
.sp
.RE
.RE
.PP
nfs4:acedup = [dontcare|reject|ignore|merge]
.RS 4
このパラメータはGPFS ACL中で遭遇した、重複したACEをSambaがどのように取り扱う かを設定する。 GPFSは同じIDのために異なったbitのために重複したACEを認めるか作成する。
.sp
以下は、異なった値のための、Sambaの動作である:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
dontcare (既定値)
\- copy the ACEs as they come
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
reject
\- stop operation and exit with error on ACL set op
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ignore
\- don\'t include the second matching ACE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
merge
\- bitwise OR the 2 ace\.flag fields and 2 ace\.mask fields of the 2 duplicate ACEs into 1 ACE
.sp
.RE
.RE
.PP
nfs4:chown = [yes|no]
.RS 4
このパラメータはファイルシステムの基礎によってサポートされる、 chownを有効または無効にする事を認める。このパラメータは、それが使うシステムの セキュリティを低下させるかもしれない事に注意して有効にすべきである。
.sp
いくつかのファイルシステムでは、chown を a) giving b) stealingと することを認めている。これは、リスクとして考える後の方である。
.sp
以下は異なった値に対するSambaの動作である:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
yes
\- ファイルシステム下でサポートするようなchownを有効にする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
no (既定値)
\- chownを無効にする
.sp
.RE
.RE
.SH "使用例"
.PP
GPFS mount は以下のように、Samba経由でエクスポートできる:
.sp
.RS 4
.nf
        \fI[samba_gpfs_share]\fR
	\fIvfs objects = gpfs\fR
	\fIpath = /test/gpfs_mount\fR
	\fInfs4: mode = special\fR
	\fInfs4: acedup = merge\fR
.fi
.RE
.SH "警告"
.PP
gpfs gplライブラリは、コンパイルと実行時にgpfs
VFS モジュールに必要である。 また、このVFSモジュールは SLES 9/10 と RHEL 4\.4で動作テストが行われている。
.SH "バージョン"
.PP
このマニュアルページは Samba バージョン 3\.2\.25用である。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.PP
GPFS VFSモジュールはVolker LendeckeとIBMの開発者によって寄贈され、作成された。
.PP
このマニュアルページは、IBM FSCCチームによって作成された。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.4 対応のものである。
.PP
このドキュメントの Samba 3\.2\.4 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
たかはしもとのぶ (monyo@samba\.gr\.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\.gr\.jp)
.sp
.RE
によって行なわれた。
