.\"     Title: vfs_streams_xattr
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/06/2008
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "VFS_STREAMS_XATTR" "8" "11/06/2008" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_streams_xattr - posix xattrs 形式で代替データを保存する
.SH "SYNOPSIS"
.HP 1
vfs objects = streams_xattr
.SH "説明"
.PP
この VFS モジュールは
\fBsamba\fR(7)
システムの一部である。
.PP
vfs_streams_xattr
は ファイルシステム中にNTFS 代替 データストリームの保存を可能にする。標準 posix ファイルシステムはファイル毎の多重データ ストリームの概念をサポートしないので、streams_xattr モジュールは posix 拡張 属性(xattrs)内にデータを保存する。これらの属性名はuser\.DosStream\."ADS\-NAME" である。
.PP
有効にされたこのモジュールによって共有されたファイルシステムは xattrs を サポートしなければならない。
.PP
ほとんどのファイルシステムで xattrs に厳しいサイズ制限があることに注意すること。 だからこのモジュールは IE のような小さいゾーン情報をストリームに保存するアプリケーション 上では動作するだろうが、ADS に大量のデータを保存するアプリケーションでは 動作しないだろう。
.SH "使用例"
.sp
.RS 4
.nf
        \fI[share]\fR
	\fIvfs objects = streams_xattr\fR
.fi
.RE
.SH "AUTHOR"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.4 対応のものである。
.PP
このドキュメントの Samba 3\.2\.4 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
たかはしもとのぶ (monyo@samba\.gr\.jp)
.sp
.RE
によって行なわれた。
